dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.7.0
  flutter_blue_plus: ^1.10.2
  http: ^0.13.5
  syncfusion_flutter_charts: ^22.1.40
  flutter_local_notifications: ^15.1.1
  intl: ^0.18.1
